Tracking api changes
linkedin/iris-relay pull request #73
Opened 2022-06-01 19:44 UTC by cshelke52889

Tested using make serve in local

2022-06-01 21:10 UTC, diegocepedaw requested changes

2022-06-01 21:10 UTC, diegocepedaw commented on configs/config.dev.yaml
> + - actions_tracking.gif
replace this with dummy value, also this shouldn't match on the filename, it should match on some previous part of the pat e.g: for /v0/tracking/file.jpg it should match to tracking not file.jpg

2022-06-01 21:11 UTC, diegocepedaw requested changes

2022-06-01 21:11 UTC, diegocepedaw commented on src/iris_relay/app.py
> +        if segments[2] in self.auth_postprocessing_list:
nit: add comment explaining that auth should be handled separately  by the function processing this endpoint

2022-06-02 02:30 UTC, cshelke52889 commented on configs/config.dev.yaml
> + - actions_tracking.gif
fixed

2022-06-02 16:22 UTC, diegocepedaw requested changes

2022-06-02 16:22 UTC, diegocepedaw commented on configs/config.dev.yaml
> + - dummy_item1
This config option should be commented out. Otherwise by default a dummy_item1 endpoint would be unauthenticated. Should't be a big issue since it is not an implemented but it is best practice to comment out these optional configs. Also maybe rename to something more descriptive like special_auth_endpoint

2022-06-02 16:22 UTC, diegocepedaw commented on src/iris_relay/app.py
> +                    if segments[2].startswith(item):
If we are going to define an exception for auth middleware for certain endpoints we should match the strings for the endpoint exactly with the configured string. While unlikely this could create a bug that skips auth for an unintended endpoint if an auth exception endpoint starts the same way as an endpoint that does not have special auth configured for it.

2022-06-02 19:21 UTC, jwon commented on configs/config.dev.yaml
> +special_auth_endpoint_list:
Let's call this `special_auth_endpoints` instead! It's not idiomatic to include the type as part of the variable name

2022-06-02 19:23 UTC, merged